version: '3.9'

services:
  postgres:
    image: postgres:13.2-alpine
    restart: unless-stopped
    env_file:
      - '.env'
    ports:
      - '$POSTGRES_PORT:5432'
    volumes:
      - postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:5.0
    restart: unless-stopped
    env_file:
      - '.env'
    ports:
      - '$PGADMIN_PORT:80'
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
  app:
    #image: 
    build: app/
    restart: unless-stopped
    env_file:
      - '.env'
    ports:
      - "8000:8000"
    networks:
      backend:
        aliases:
          - web
  
networks:
  backend:
    driver: bridge
