version: '3.9'

services:
#  postgres:
#    image: postgres:13.2-alpine
#    restart: unless-stopped
#    env_file:
#      - ".env"
#    ports:
#      - "$POSTGRES_PORT:5432"
#    volumes:
#      - postgres:/var/lib/postgresql/data

  app:
    build: app/
    restart: unless-stopped
    env_file:
      - ".env"
    ports:
      - "8000:80"
#    depends_on:
#      - postgres

#  pgadmin:
#    image: dpage/pgadmin4
#    restart: unless-stopped
#    env_file:
#      - ".env"
#    ports:
#      - "$PGADMIN_PORT:80"
#    volumes:
#      - pgadmin:/var/lib/pgadmin
#    depends_on:
#      - postgres

#volumes:
#  postgres:
#    driver: local
#    name: postgres
  
#  pgadmin:
#    driver: local
#    name: pgadmin
      
